import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "es";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navbar
    "nav.company": "Company",
    "nav.products": "Products",
    "nav.operations": "Operations",
    "nav.services": "Services",
    "nav.compliance": "Compliance",
    "nav.contact": "Contact",

    // Hero
    "hero.badge": "Peru's Premier Mining Company",
    "hero.title1": "Driving the",
    "hero.title2": "Future with",
    "hero.title3": "Quality Minerals",
    "hero.subtitle": "Connecting Peru's rich natural resources with global markets through sustainable extraction and world-class quality assurance.",
    "hero.cta1": "Explore Products",
    "hero.cta2": "Watch Story",
    "hero.stat1": "Concessions",
    "hero.stat2": "Founded",
    "hero.stat3": "Quality",
    "hero.scroll": "Scroll",

    // Company Profile
    "company.section": "Company Profile",
    "company.title1": "Building a ",
    "company.title2": "Legacy",
    "company.subtitle": "Founded in 2019 by entrepreneur Andrea Marcon, Inca Phyto has evolved from an agro-export pioneer into a dynamic force in Peru's mineral extraction industry.",
    "company.summary": "Executive Summary",
    "company.summary.text": "A dynamic Peruvian enterprise connecting the country's natural resources with the global market. Starting with sustainable botanical products, we strategically diversified into high-quality mineral extraction.",
    "company.divisions": "Active Divisions",
    "company.concessions": "Mining Concessions",
    "company.agro": "Agro-Export Division",
    "company.agro.desc": "Sustainable botanical products",
    "company.mining": "Mining Division",
    "company.mining.desc": "High-quality coal extraction",
    "company.feature1": "Global Reach",
    "company.feature1.desc": "Connecting Peru's resources with international markets worldwide",
    "company.feature2": "Strategic Focus",
    "company.feature2.desc": "Specialized in high-quality anthracite and bituminous coal",
    "company.feature3": "Growth Vision",
    "company.feature3.desc": "Continuous expansion and diversification since 2019",
    "company.feature4": "Expert Team",
    "company.feature4.desc": "Led by industry veterans with decades of experience",

    // Products
    "products.section": "Products & Services",
    "products.title1": "Portafolio de ",
    "products.title2": "Minerales",
    "products.title3": " Premium",
    "products.subtitle": "We are exporters of various types of minerals, specializing in ANTHRACITE, COPPER, ZINC, LEAD, and products from ANTAMINA through rigorous quality control and sustainable practices.",
    "products.anthracite": "Anthracite Coal",
    "products.anthracite.tag": "Premium Grade",
    "products.anthracite.desc": "High-grade coal used in metallurgy with exceptional carbon content and minimal impurities. Available in multiple granulometries.",
    "products.copper": "Copper",
    "products.copper.tag": "High Conductivity",
    "products.copper.desc": "Premium copper ore for industrial and electrical applications. Essential for modern technology and infrastructure.",
    "products.zinc": "Zinc",
    "products.zinc.tag": "Corrosion Resistant",
    "products.zinc.desc": "High-quality zinc for galvanization and alloy production. Critical for construction and manufacturing industries.",
    "products.lead": "Lead",
    "products.lead.tag": "Industrial Grade",
    "products.lead.desc": "Premium lead ore for battery production and industrial applications. Reliable supply for global markets.",
    "products.feature1": "1½'' to 3'' size",
    "products.feature2": "1/2 to 1½'' size",
    "products.feature3": "1/8 to ½'' size",
    "products.feature4": "0 x 1/8'' injection grade",
    "products.feature5": "High Conductivity",
    "products.feature6": "Industrial Grade",
    "products.feature7": "Consistent Quality",
    "products.feature8": "Global Export",
    "products.feature9": "Corrosion Resistant",
    "products.feature10": "Galvanization Ready",
    "products.feature11": "Battery Grade",
    "products.feature12": "Premium Quality",
    "products.learnMore": "Learn More",
    "products.division": "Mining & Extraction Division",
    "products.expansion": "Strategic Expansion",
    "products.expansion.text": "Our division is oriented to satisfy international energy demand through market analysis and strategic expansion. We focus on extraction, processing, and export logistics of premium coal products.",
    "products.extraction": "Extraction",
    "products.processing": "Processing",
    "products.export": "Export",
    "products.anthracite.gallery": "Anthracite Granulometries Available",
    "products.anthracite.size1": "1½'' to 3'' or larger size for melting",
    "products.anthracite.size2": "1/2 to 1½'' for load or basket",
    "products.anthracite.size3": "1/8 to ½'' for adjustment",
    "products.anthracite.size4": "0 x 1/8'' for injection",

    // Operations
    "operations.section": "Strategic Assets & Operations",
    "operations.title1": "Powered by ",
    "operations.title2": "Excellence",
    "operations.subtitle": "Our growth is built on tangible assets and legal mining concessions located in highly productive zones across Peru.",
    "operations.concessions": "5 Concessions",
    "operations.rights": "Exclusive extraction rights",
    "operations.trujillo": "Trujillo",
    "operations.trujillo.region": "La Libertad",
    "operations.trujillo.desc": "Strategic port access for Asian and Western markets",
    "operations.oyon": "Oyón",
    "operations.oyon.region": "Lima",
    "operations.oyon.desc": "Traditional mining hub with premium coal deposits",
    "operations.map": "Peru Mining Regions",
    "operations.network": "Global Export Network",
    "operations.network.desc": "Integrated supply chain from the Andes to international ports",
    "operations.step1": "Extraction",
    "operations.step1.desc": "High-altitude mining in the Andes",
    "operations.step2": "Processing",
    "operations.step2.desc": "Quality control & specification",
    "operations.step3": "Export",
    "operations.step3.desc": "Port logistics & shipping",
    "operations.ports": "Strategic Port Access",
    "operations.ports.desc": "Primary export through Callao and Salaverry ports, with direct routes to Asian and Western markets.",

    // Services
    "services.section": "Value Added Services",
    "services.title1": "Why Choose ",
    "services.title2": "Inca Phyto?",
    "services.subtitle": "Our commitment to excellence extends beyond extraction. We deliver comprehensive value-added services that set us apart in the global market.",
    "services.quality": "Quality Assurance",
    "services.quality.sub": "& Certification",
    "services.quality.desc": "Quality control as the core of compliance, ensuring final products meet all contractual specifications.",
    "services.inspection": "Third-Party",
    "services.inspection.sub": "Inspection",
    "services.inspection.desc": "Pre-shipment inspection and sampling by globally recognized entities like SGS and Bureau Veritas.",
    "services.custom": "Specification",
    "services.custom.sub": "Customization",
    "services.custom.desc": "Custom adjustments in moisture, ash, sulfur, and other parameters per buyer requirements.",
    "services.trace": "Full",
    "services.trace.sub": "Traceability",
    "services.trace.desc": "Complete tracking system from mine face to final shipment, with auditable origin records.",
    "services.certified": "Certified Standards",
    "services.verified": "Verified Quality",
    "services.support": "Support Available",
    "services.satisfaction": "Satisfaction",

    // Compliance
    "compliance.section": "Contract Compliance",
    "compliance.title1": "Flexible ",
    "compliance.title2": "Partnership",
    "compliance.subtitle": "We're committed to traceability and quality with flexible contractual and logistics options tailored to your business needs.",
    "compliance.incoterms": "Incoterms Options",
    "compliance.fob": "FOB",
    "compliance.fob.desc": "Free On Board at Peruvian ports (Callao, Salaverry)",
    "compliance.cif": "CIF",
    "compliance.cif.desc": "Cost, Insurance & Freight to buyer's destination port",
    "compliance.volume": "Shipping Volume",
    "compliance.panamax": "Panamax",
    "compliance.panamax.desc": "Large-scale bulk shipments for major buyers",
    "compliance.breakbulk": "Break-bulk",
    "compliance.breakbulk.desc": "Flexible smaller shipments as needed",
    "compliance.delivery": "Delivery Scheduling",
    "compliance.laycan": "Laycan Windows",
    "compliance.laycan.desc": "Negotiable loading windows",
    "compliance.inventory": "Inventory Sync",
    "compliance.inventory.desc": "Adapted to buyer's stock and port congestion",
    "compliance.financial": "Financial Flexibility",
    "compliance.financial.desc": "Multiple payment mechanisms and pricing models to suit your procurement strategy",
    "compliance.lc": "Letter of Credit",
    "compliance.lc.desc": "Irrevocable LC for secure transactions",
    "compliance.sblc": "Standby LC",
    "compliance.sblc.desc": "SBLC for term contracts",
    "compliance.pricing": "Pricing Models",
    "compliance.pricing.desc": "Fixed or indexed (Argus, Platts)",
    "compliance.foundation": "Foundation of Operation",
    "compliance.category": "Category",
    "compliance.requirement": "Compliance Requirement",
    "compliance.flexibility": "Flexibility Component",
    "compliance.extraction": "Extraction",
    "compliance.extraction.req": "MEM parameters & concession requirements",
    "compliance.extraction.flex": "Scalable production based on demand",
    "compliance.safety": "Safety & Labor",
    "compliance.safety.req": "Peruvian labor laws & OSINERGMIN standards",
    "compliance.safety.flex": "Multi-skilled adaptable workforce",
    "compliance.processing": "Processing",
    "compliance.processing.req": "Environmental management under EIA",
    "compliance.processing.flex": "Adjustable specifications (CV, ash, sulfur)",

    // Footer
    "footer.section": "Get In Touch",
    "footer.thankyou": "Thank You",
    "footer.subtitle": "Ready to discuss your coal procurement needs? Our team is here to help you find the right solution.",
    "footer.contact": "Contact Information",
    "footer.address": "Address",
    "footer.phone": "Phone",
    "footer.email": "Email",
    "footer.newsletter": "Stay Updated",
    "footer.newsletter.desc": "Subscribe to our newsletter for the latest updates on products and market insights.",
    "footer.subscribe": "Subscribe",
    "footer.follow": "Follow Us",
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.specialMention": "Special Partnership",
    "footer.partnerText": "Strategic alliance with our US partner",
  },
  es: {
    // Navbar
    "nav.company": "Empresa",
    "nav.products": "Productos",
    "nav.operations": "Operaciones",
    "nav.services": "Servicios",
    "nav.compliance": "Cumplimiento",
    "nav.contact": "Contacto",

    // Hero
    "hero.badge": "La Empresa Minera Premier del Perú",
    "hero.title1": "Impulsando el",
    "hero.title2": "Futuro con",
    "hero.title3": "Minerales de Calidad",
    "hero.subtitle": "Conectando los ricos recursos naturales del Perú con los mercados globales a través de extracción sostenible y aseguramiento de calidad de clase mundial.",
    "hero.cta1": "Explorar Productos",
    "hero.cta2": "Ver Historia",
    "hero.stat1": "Concesiones",
    "hero.stat2": "Fundada",
    "hero.stat3": "Calidad",
    "hero.scroll": "Desplazar",

    // Company Profile
    "company.section": "Perfil Corporativo",
    "company.title1": "Construyendo un ",
    "company.title2": "Legado",
    "company.subtitle": "Fundada en 2019 por el empresario Andrea Marcon, Inca Phyto ha evolucionado de un pionero agroexportador a una fuerza dinámica en la industria de extracción mineral del Perú.",
    "company.summary": "Resumen Ejecutivo",
    "company.summary.text": "Una empresa peruana dinámica que conecta los recursos naturales del país con el mercado global. Comenzando con productos botánicos sostenibles, nos diversificamos estratégicamente hacia la extracción mineral de alta calidad.",
    "company.divisions": "Divisiones Activas",
    "company.concessions": "Concesiones Mineras",
    "company.agro": "División Agroexportadora",
    "company.agro.desc": "Productos botánicos sostenibles",
    "company.mining": "División Minera",
    "company.mining.desc": "Extracción de carbón de alta calidad",
    "company.feature1": "Alcance Global",
    "company.feature1.desc": "Conectando los recursos del Perú con mercados internacionales en todo el mundo",
    "company.feature2": "Enfoque Estratégico",
    "company.feature2.desc": "Especializados en antracita y carbón bituminoso de alta calidad",
    "company.feature3": "Visión de Crecimiento",
    "company.feature3.desc": "Expansión y diversificación continua desde 2019",
    "company.feature4": "Equipo Experto",
    "company.feature4.desc": "Liderado por veteranos de la industria con décadas de experiencia",

    // Products
    "products.section": "Productos y Servicios",
    "products.title1": "Portafolio de ",
    "products.title2": "Minerales",
    "products.title3": " Premium",
    "products.subtitle": "Somos exportadores de varios tipos de minerales, especializados en ANTRACITA, COBRE, ZINC, PLOMO y productos de ANTAMINA a través de un riguroso control de calidad y prácticas sostenibles.",
    "products.anthracite": "Carbón Antracita",
    "products.anthracite.tag": "Grado Premium",
    "products.anthracite.desc": "Carbón de alto grado usado en metalurgia con excepcional contenido de carbono y mínimas impurezas. Disponible en varias granulometrías.",
    "products.copper": "Cobre",
    "products.copper.tag": "Alta Conductividad",
    "products.copper.desc": "Mineral de cobre premium para aplicaciones industriales y eléctricas. Esencial para tecnología moderna e infraestructura.",
    "products.zinc": "Zinc",
    "products.zinc.tag": "Resistente a Corrosión",
    "products.zinc.desc": "Zinc de alta calidad para galvanización y producción de aleaciones. Crítico para industrias de construcción y manufactura.",
    "products.lead": "Plomo",
    "products.lead.tag": "Grado Industrial",
    "products.lead.desc": "Mineral de plomo premium para producción de baterías y aplicaciones industriales. Suministro confiable para mercados globales.",
    "products.feature1": "Tamaño 1½'' a 3''",
    "products.feature2": "Tamaño 1/2 a 1½''",
    "products.feature3": "Tamaño 1/8 a ½''",
    "products.feature4": "0 x 1/8'' para inyección",
    "products.feature5": "Alta Conductividad",
    "products.feature6": "Grado Industrial",
    "products.feature7": "Calidad Consistente",
    "products.feature8": "Exportación Global",
    "products.feature9": "Resistente a Corrosión",
    "products.feature10": "Listo para Galvanizar",
    "products.feature11": "Grado para Baterías",
    "products.feature12": "Calidad Premium",
    "products.learnMore": "Más Información",
    "products.division": "División de Minería y Extracción",
    "products.expansion": "Expansión Estratégica",
    "products.expansion.text": "Nuestra división está orientada a satisfacer la demanda energética internacional a través del análisis de mercado y la expansión estratégica. Nos enfocamos en la extracción, procesamiento y logística de exportación de productos de carbón premium.",
    "products.extraction": "Extracción",
    "products.processing": "Procesamiento",
    "products.export": "Exportación",
    "products.anthracite.gallery": "Granulometrías de Antracita Disponibles",
    "products.anthracite.size1": "1½'' a 3'' o mayor tamaño para fundición",
    "products.anthracite.size2": "1/2 a 1½'' para carga o canasta",
    "products.anthracite.size3": "1/8 a ½'' para ajuste",
    "products.anthracite.size4": "0 x 1/8'' para inyección",

    // Operations
    "operations.section": "Activos Estratégicos y Operaciones",
    "operations.title1": "Impulsados por la ",
    "operations.title2": "Excelencia",
    "operations.subtitle": "Nuestro crecimiento se basa en activos tangibles y concesiones mineras legales ubicadas en zonas altamente productivas del Perú.",
    "operations.concessions": "5 Concesiones",
    "operations.rights": "Derechos exclusivos de extracción",
    "operations.trujillo": "Trujillo",
    "operations.trujillo.region": "La Libertad",
    "operations.trujillo.desc": "Acceso portuario estratégico para mercados asiáticos y occidentales",
    "operations.oyon": "Oyón",
    "operations.oyon.region": "Lima",
    "operations.oyon.desc": "Centro minero tradicional con depósitos de carbón premium",
    "operations.map": "Regiones Mineras del Perú",
    "operations.network": "Red de Exportación Global",
    "operations.network.desc": "Cadena de suministro integrada desde los Andes hasta puertos internacionales",
    "operations.step1": "Extracción",
    "operations.step1.desc": "Minería de alta montaña en los Andes",
    "operations.step2": "Procesamiento",
    "operations.step2.desc": "Control de calidad y especificación",
    "operations.step3": "Exportación",
    "operations.step3.desc": "Logística portuaria y envío",
    "operations.ports": "Acceso Portuario Estratégico",
    "operations.ports.desc": "Exportación principal a través de los puertos del Callao y Salaverry, con rutas directas a mercados asiáticos y occidentales.",

    // Services
    "services.section": "Servicios de Valor Agregado",
    "services.title1": "¿Por Qué Elegir ",
    "services.title2": "Inca Phyto?",
    "services.subtitle": "Nuestro compromiso con la excelencia se extiende más allá de la extracción. Ofrecemos servicios integrales de valor agregado que nos distinguen en el mercado global.",
    "services.quality": "Aseguramiento de Calidad",
    "services.quality.sub": "y Certificación",
    "services.quality.desc": "Control de calidad como núcleo del cumplimiento, asegurando que los productos finales cumplan con todas las especificaciones contractuales.",
    "services.inspection": "Inspección de",
    "services.inspection.sub": "Terceros",
    "services.inspection.desc": "Inspección y muestreo previo al embarque por entidades reconocidas globalmente como SGS y Bureau Veritas.",
    "services.custom": "Personalización de",
    "services.custom.sub": "Especificaciones",
    "services.custom.desc": "Ajustes personalizados en humedad, ceniza, azufre y otros parámetros según los requisitos del comprador.",
    "services.trace": "Trazabilidad",
    "services.trace.sub": "Completa",
    "services.trace.desc": "Sistema de seguimiento completo desde el frente de mina hasta el embarque final, con registros de origen auditables.",
    "services.certified": "Estándares Certificados",
    "services.verified": "Calidad Verificada",
    "services.support": "Soporte Disponible",
    "services.satisfaction": "Satisfacción",

    // Compliance
    "compliance.section": "Cumplimiento Contractual",
    "compliance.title1": "Asociación ",
    "compliance.title2": "Flexible",
    "compliance.subtitle": "Estamos comprometidos con la trazabilidad y calidad con opciones contractuales y logísticas flexibles adaptadas a las necesidades de su negocio.",
    "compliance.incoterms": "Opciones de Incoterms",
    "compliance.fob": "FOB",
    "compliance.fob.desc": "Libre a Bordo en puertos peruanos (Callao, Salaverry)",
    "compliance.cif": "CIF",
    "compliance.cif.desc": "Costo, Seguro y Flete al puerto de destino del comprador",
    "compliance.volume": "Volumen de Envío",
    "compliance.panamax": "Panamax",
    "compliance.panamax.desc": "Envíos a granel a gran escala para grandes compradores",
    "compliance.breakbulk": "Break-bulk",
    "compliance.breakbulk.desc": "Envíos más pequeños y flexibles según sea necesario",
    "compliance.delivery": "Programación de Entrega",
    "compliance.laycan": "Ventanas Laycan",
    "compliance.laycan.desc": "Ventanas de carga negociables",
    "compliance.inventory": "Sincronización de Inventario",
    "compliance.inventory.desc": "Adaptado al stock del comprador y congestión portuaria",
    "compliance.financial": "Flexibilidad Financiera",
    "compliance.financial.desc": "Múltiples mecanismos de pago y modelos de precios para adaptarse a su estrategia de adquisición",
    "compliance.lc": "Carta de Crédito",
    "compliance.lc.desc": "LC irrevocable para transacciones seguras",
    "compliance.sblc": "LC Standby",
    "compliance.sblc.desc": "SBLC para contratos a término",
    "compliance.pricing": "Modelos de Precios",
    "compliance.pricing.desc": "Fijo o indexado (Argus, Platts)",
    "compliance.foundation": "Base de Operación",
    "compliance.category": "Categoría",
    "compliance.requirement": "Requisito de Cumplimiento",
    "compliance.flexibility": "Componente de Flexibilidad",
    "compliance.extraction": "Extracción",
    "compliance.extraction.req": "Parámetros del MEM y requisitos de concesión",
    "compliance.extraction.flex": "Producción escalable según demanda",
    "compliance.safety": "Seguridad y Trabajo",
    "compliance.safety.req": "Leyes laborales peruanas y normas OSINERGMIN",
    "compliance.safety.flex": "Fuerza laboral adaptable y multicapacitada",
    "compliance.processing": "Procesamiento",
    "compliance.processing.req": "Gestión ambiental bajo EIA",
    "compliance.processing.flex": "Especificaciones ajustables (CV, ceniza, azufre)",

    // Footer
    "footer.section": "Contáctenos",
    "footer.thankyou": "Gracias",
    "footer.subtitle": "¿Listo para discutir sus necesidades de adquisición de carbón? Nuestro equipo está aquí para ayudarlo a encontrar la solución correcta.",
    "footer.contact": "Información de Contacto",
    "footer.address": "Dirección",
    "footer.phone": "Teléfono",
    "footer.email": "Correo",
    "footer.newsletter": "Manténgase Informado",
    "footer.newsletter.desc": "Suscríbase a nuestro boletín para las últimas actualizaciones sobre productos e información del mercado.",
    "footer.subscribe": "Suscribirse",
    "footer.follow": "Síguenos",
    "footer.rights": "Todos los derechos reservados.",
    "footer.privacy": "Política de Privacidad",
    "footer.terms": "Términos de Servicio",
    "footer.specialMention": "Mención Especial",
    "footer.partnerText": "Alianza estratégica con nuestro socio en EE.UU.",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
